# Servidor
server.port=8080

# Postgres
spring.datasource.url=jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}
spring.datasource.username=${PGUSER}
spring.datasource.password=${PGPASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# HiveMQ
hivemq.host=${HIVEMQ_HOST}
hivemq.port=${HIVEMQ_PORT}
hivemq.username=${HIVEMQ_USER}
hivemq.password=${HIVEMQ_PASSWORD}

# MQTT Tópicos
mqtt.topic.leitura=sensores/gas/leitura
mqtt.topic.alerta=sensores/gas/alerta
mqtt.topic.status=sensores/gas/status